grafana:
  enabled: true
# prometheus:
#   server:
#     persistentVolume:
#       enabled: true
#   prometheusSpec:
#     storageSpec:
#       volumeClaimTemplate:
#       - metadata:
#             name: prometheus-pv
#         spec:
#           accessModes: ["ReadWriteOnce"]
#           resources:
#             requests:
#               storage: 4Gi
