apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
  - ingress.yml
  - secret.yml
  - release.yml
configMapGenerator:
  - name: loki-values
    files:
      - values.yml=values.yml
configurations:
  - kustomizeconfig.yml
